### ISSUE TITLE
Q: Some questions regarding this project

### ISSUE THREAD

**Issue by Blacksheep70** [DreamingRaven/RavenSLA#7]
Hi,

1.) Is this project still alive? What is your current status?
2.) The space under the vat looks not large enough for me to print the whole space with a laser. I would expect at least 50 cm distance to the vat. How do you realize that?
3.) I don't see any code for the galvo... any comment on this?

**Comment by DreamingRaven** [comment]
1) no this project is currently not being furthered
2) the space under the vat is printable but you have to take care as there is a certain element of warping at the extremes as a single step of the steppers will result in a larger distance, which needs to be handled problematically. 
3) what do you mean by galvo code, the ESP code for handling the interpreted G code is: https://github.com/DreamingRaven/RavenSLA/tree/master/Esp8266 but for actually parsing the G code into a format that the ESP can use: https://github.com/DreamingRaven/RavenSLA/blob/master/parser/Parser.cpp

Hope that helps and apologies for the delay, as I said this is not currently being maintained or developed as I am currently focusing on nemesyst https://github.com/DreamingRaven/Nemesyst

**Comment by DreamingRaven** [comment]
I have closed this issue as it has been a long time, feel free to re-open it should you need more deets.
